#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
export PROJECT_ROOT="${PROJECT_ROOT:-$(cd "${SCRIPT_DIR}/.." && pwd)}"
cd "${PROJECT_ROOT}"

export PYTHON_BIN="${PYTHON_BIN:-python}"
export PYTHONPATH="${PROJECT_ROOT}:${PYTHONPATH:-}"
export PYTHONUNBUFFERED=1
export PYTORCH_CUDA_ALLOC_CONF="${PYTORCH_CUDA_ALLOC_CONF:-expandable_segments:True}"

export CUDA_VISIBLE_DEVICES="${CUDA_VISIBLE_DEVICES:-0}"
export DEVICE="${DEVICE:-cuda:0}"
export FINAL_SEEDS="${FINAL_SEEDS:-1,11,111}"
export TRAIN_EPOCHS="${TRAIN_EPOCHS:-700}"
export EARLY_STOP="${EARLY_STOP:-1}"
export EARLY_STOP_MIN_EPOCHS="${EARLY_STOP_MIN_EPOCHS:-0}"
export EARLY_STOP_PATIENCE="${EARLY_STOP_PATIENCE:-30}"
export EARLY_STOP_MIN_DELTA="${EARLY_STOP_MIN_DELTA:-1e-4}"
export EARLY_STOP_MONITOR="${EARLY_STOP_MONITOR:-loss_total}"
export EARLY_STOP_RESTORE_BEST="${EARLY_STOP_RESTORE_BEST:-0}"

export RUN_PROTEOGENOMICS_TASKS=1
export RUN_METABOLOMICS_TASKS=0
export FORCE_TASK_RETRAIN="${FORCE_TASK_RETRAIN:-1}"

export USE_HE_TRANSFORMER="${USE_HE_TRANSFORMER:-1}"
export HE_GLOBAL_TRANSFORMER_LAYERS="${HE_GLOBAL_TRANSFORMER_LAYERS:-2}"
export HE_GLOBAL_TRANSFORMER_HEADS="${HE_GLOBAL_TRANSFORMER_HEADS:-4}"
export HE_GLOBAL_TRANSFORMER_TOKENS="${HE_GLOBAL_TRANSFORMER_TOKENS:-4}"
export HE_GLOBAL_TRANSFORMER_FF_MULT="${HE_GLOBAL_TRANSFORMER_FF_MULT:-2.0}"
export HE_LOCAL_TRANSFORMER_LAYERS="${HE_LOCAL_TRANSFORMER_LAYERS:-1}"
export HE_LOCAL_TRANSFORMER_HEADS="${HE_LOCAL_TRANSFORMER_HEADS:-8}"
export HE_LOCAL_TRANSFORMER_CHUNK_SIZE="${HE_LOCAL_TRANSFORMER_CHUNK_SIZE:-512}"
export HE_LOCAL_TRANSFORMER_FF_MULT="${HE_LOCAL_TRANSFORMER_FF_MULT:-2.0}"
export HE_LOCAL_TRANSFORMER_RESIDUAL_SCALE="${HE_LOCAL_TRANSFORMER_RESIDUAL_SCALE:-0.5}"

export LAMBDA_TARGET="${LAMBDA_TARGET:-1.0}"
export LAMBDA_CYCLE="${LAMBDA_CYCLE:-0.2}"
export LAMBDA_PARTIAL_CYCLE="${LAMBDA_PARTIAL_CYCLE:-0.2}"
export LAMBDA_KB="${LAMBDA_KB:-0.05}"
export LAMBDA_ALIGN="${LAMBDA_ALIGN:-0.02}"
export LAMBDA_FULL="${LAMBDA_FULL:-1.0}"
export LAMBDA_PARTIAL="${LAMBDA_PARTIAL:-0.0}"
export LAMBDA_LATENT="${LAMBDA_LATENT:-0.0}"
export LAMBDA_RECON="${LAMBDA_RECON:-0.0}"
export LAMBDA_GRAPH="${LAMBDA_GRAPH:-0.0}"
export LAMBDA_PCC="${LAMBDA_PCC:-0.0}"
export LAMBDA_ORTHO="${LAMBDA_ORTHO:-0.0}"
export LAMBDA_DGI="${LAMBDA_DGI:-0.0}"
export TARGET_SOFT_ALPHA="${TARGET_SOFT_ALPHA:-0.0}"

export PROTEO_DATA_ROOT="${PROTEO_DATA_ROOT:-${PROJECT_ROOT}/data/spatch}"
export PROTEO_SAMPLE1="${PROTEO_SAMPLE1:-protein}"
export PROTEO_SAMPLE2="${PROTEO_SAMPLE2:-gene}"

export RUN_TAG="${RUN_TAG:-proteogenomics_dynamic_gate_700_pat30}"
export SAVE_PARENT="${SAVE_PARENT:-${PROJECT_ROOT}/results/akg_omics_proteogenomics_dynamic_gate}"
export FUSION_GATE_TEMPERATURE="${FUSION_GATE_TEMPERATURE:-0.5}"
export FUSION_MODALITY_DROPOUT="${FUSION_MODALITY_DROPOUT:-0.15}"
export LAMBDA_FUSION_GATE="${LAMBDA_FUSION_GATE:-0.005}"
export FUSION_GATE_DIVERSITY_WEIGHT="${FUSION_GATE_DIVERSITY_WEIGHT:-0.1}"

export KNOWLEDGE_AGENT_LLM_PROVIDER="${KNOWLEDGE_AGENT_LLM_PROVIDER:-deepseek}"
export KNOWLEDGE_AGENT_LLM_MODEL="${KNOWLEDGE_AGENT_LLM_MODEL:-deepseek-v4-pro}"
export KNOWLEDGE_AGENT_LLM_ENDPOINT="${KNOWLEDGE_AGENT_LLM_ENDPOINT:-https://api.deepseek.com/v1/chat/completions}"
export KNOWLEDGE_AGENT_LLM_API_KEY="${KNOWLEDGE_AGENT_LLM_API_KEY:-${DEEPSEEK_API_KEY:-}}"

bash akg_omics/train_rule_agent_core.sh