#!/usr/bin/env bash
set -euo pipefail

if [[ $# -ne 2 ]]; then
  echo "Usage: $0 <gpu_id> <full|no_kb|no_dynamic>" >&2
  exit 2
fi

GPU_ID="$1"
VARIANT="$2"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="${PROJECT_ROOT:-$(cd "${SCRIPT_DIR}/.." && pwd)}"
RESULT_ROOT="${RESULT_ROOT:-${PROJECT_ROOT}/results/external_knowledge_analysis}"
export SAVE_ROOT="${RESULT_ROOT}/task3_4806gene_seed1/${VARIANT}/run"

case "${VARIANT}" in
  full)
    export LAMBDA_KB=0.05
    export DISABLE_KB_FUSION=0
    export DISABLE_DYNAMIC_RETRIEVER=0
    ;;
  no_kb)
    export LAMBDA_KB=0.0
    export DISABLE_KB_FUSION=1
    export DISABLE_DYNAMIC_RETRIEVER=1
    ;;
  no_dynamic)
    export LAMBDA_KB=0.05
    export DISABLE_KB_FUSION=0
    export DISABLE_DYNAMIC_RETRIEVER=1
    ;;
  *)
    echo "Unsupported variant: ${VARIANT}" >&2
    exit 2
    ;;
esac

cd "${PROJECT_ROOT}"
mkdir -p "${RESULT_ROOT}/logs"

export RUN_TAG="dynamic_kb_task3_seed1_${VARIANT}_700_pat30"
export CUDA_VISIBLE_DEVICES="${GPU_ID}"
export DEVICE=cuda:0
export PYTHON_BIN="${PYTHON_BIN:-python}"
export PYTHONPATH="${PROJECT_ROOT}:${PYTHONPATH:-}"
export PYTHONUNBUFFERED=1
export PYTORCH_CUDA_ALLOC_CONF="${PYTORCH_CUDA_ALLOC_CONF:-expandable_segments:True}"

export FINAL_SEEDS=1
export TRAIN_EPOCHS=700
export EARLY_STOP=1
export EARLY_STOP_MIN_EPOCHS=0
export EARLY_STOP_PATIENCE=30
export EARLY_STOP_MIN_DELTA=1e-4
export EARLY_STOP_MONITOR=loss_total
export EARLY_STOP_RESTORE_BEST=0

export RUN_PROTEOGENOMICS_TASKS=1
export RUN_METABOLOMICS_TASKS=0
export PROTEO_TASK_FILTER=3
export PROTEO_GENE_TOPK=4806
export PROTEO_KB_REQUESTED_MODE=rule-only
export USE_PROTEO_KB_AGENT=0
export REQUIRE_PROTEO_KB_LLM_AGENT=0
export FORCE_TASK_RETRAIN=1
export PROTEO_TASK_CACHE_VERSION="dynamic_kb_${VARIANT}"

export ENABLE_DETAILED_ANALYSIS=1
export ENABLE_KB_DYNAMIC_EXPORT=1
export TOP_FEATURE_N=20
export PLOT_TOP_FEATURE_N=5

export USE_HE_TRANSFORMER=1
export HE_GLOBAL_TRANSFORMER_LAYERS=2
export HE_GLOBAL_TRANSFORMER_HEADS=4
export HE_GLOBAL_TRANSFORMER_TOKENS=4
export HE_GLOBAL_TRANSFORMER_FF_MULT=2.0
export HE_LOCAL_TRANSFORMER_LAYERS=1
export HE_LOCAL_TRANSFORMER_HEADS=8
export HE_LOCAL_TRANSFORMER_CHUNK_SIZE=512
export HE_LOCAL_TRANSFORMER_FF_MULT=2.0
export HE_LOCAL_TRANSFORMER_RESIDUAL_SCALE=0.5

export LAMBDA_TARGET=1.0
export LAMBDA_CYCLE=0.2
export LAMBDA_PARTIAL_CYCLE=0.2
export LAMBDA_ALIGN=0.02
export LAMBDA_FULL=1.0
export LAMBDA_PARTIAL=0.0
export LAMBDA_LATENT=0.0
export LAMBDA_RECON=0.0
export LAMBDA_GRAPH=0.0
export LAMBDA_PCC=0.0
export LAMBDA_ORTHO=0.0
export LAMBDA_DGI=0.0
export TARGET_SOFT_ALPHA=0.0

export FUSION_GATE_TEMPERATURE=0.5
export FUSION_MODALITY_DROPOUT=0.15
export LAMBDA_FUSION_GATE=0.005
export FUSION_GATE_DIVERSITY_WEIGHT=0.1

export PROTEO_DATA_ROOT="${PROTEO_DATA_ROOT:-${PROJECT_ROOT}/data/spatch}"
export PROTEO_SAMPLE1=protein
export PROTEO_SAMPLE2=gene

exec "${PYTHON_BIN}" -u -m akg_omics.run